packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  electron-sparkle-updater: true
  electron-winstaller: false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@angular/common@22.1.2'
  - '@angular/compiler@22.1.2'
  - '@angular/core@22.1.2'
  - '@angular/platform-browser@22.1.2'
  - '@angular-devkit/architect@0.2201.4'
  - '@angular-devkit/core@22.1.4'
  - '@angular-devkit/schematics@22.1.4'
  - '@angular/build@22.1.4'
  - '@angular/cli@22.1.4'
  - '@angular/compiler-cli@22.1.2'
  - '@schematics/angular@22.1.4'
  - '@angular/forms@22.1.2'
